### ISSUE TITLE
I can push a Boxy to Yolo format script

### ISSUE THREAD

**Issue by Harsh-Gill** [karstenBehrendt/boxy#10]
I've been using this dataset and i had a problem with formatting and wrote some custom code that can convert this boxy dataset to the yolo format which is ,

<object-class> <x> <y> <width> <height>
0 45 55 29 67
1 99 83 28 44

Let me know if i can push it to this repo to help you or anyone else. Thanks!

**Comment by karstenBehrendt** [comment]
Hi! Yes, you can submit a data conversion script via a pull request. I will pretty much only make sure that it is general enough to be used by others, i.e., has arguments to set the input and output location, and is minimally documented
