### ISSUE TITLE
Do the x1,y1,x2,y2 in AABB means the left-top point(x1, y1) and the right-bottom point(x2, y2)?

### ISSUE THREAD

**Issue by frederichen01** [karstenBehrendt/boxy#12]

**Comment by karstenBehrendt** [comment]
Is this description up to date? I believe a higher value on the y axis means a lower point within the image
https://github.com/karstenBehrendt/boxy/tree/master/label_file_scripts

**Comment by karstenBehrendt** [comment]
Closing after months without response
