### ISSUE TITLE
7 missing bags in train.json ?

### ISSUE THREAD

**Issue by chenchr** [karstenBehrendt/boxy#2]
Hi. Thanks for the awesome dataset. After unzip the file and traverse the path from the json file, I found there are total 7 bag absent, which are the following:
```
10-04-13-52-40
10-10-18-25-04
10-26-17-55-06
10-26-18-38-03
10-30-19-24-32
11-01-10-07-39
```
I can not found the download link of these bags.
Any ideas ? 
Thanks.

**Comment by karstenBehrendt** [comment]
Hi @chenchr ,
I am terribly sorry for not responding earlier. I apparently did not have notifications setup for this repo and nobody contacted me about missing files so far. That is extremely disappointing when considering that it has been online for a year and the amount of work that went into it. I'm now going through all open issues.

I uploaded the missing files. They were already on the server but not linked within the download page. They are linked now https://boxy-dataset.com/boxy/download

Sorry about that. That was extremely disappointing.
