### ISSUE TITLE
Where is athena_ml.helper_scripts.int_round 

### ISSUE THREAD

**Issue by r00ta** [karstenBehrendt/boxy#5]
The dataset provided by Bosch is really nice, but it's quite hard to find useful info and some scripts about that. 

Actually it is almost impossible to run the examples, a requirements.txt file would help first of all

**Comment by karstenBehrendt** [comment]
Hi @r00ta , Sorry for the super late response. I wasn't getting notifications for this repo. 
 edd0d8ea122ba985b47a7a61eb3135c6f4bb7903 fixes this
