### ISSUE TITLE
Can't find the script  object_detection.utils

### ISSUE THREAD

**Issue by yazeedhasan97** [karstenBehrendt/boxy#8]
Hi @karstenBehrendt 

I cant find the `object_detection.utils` modul 

it keeps givin an error at 
`from object_detection.utils import dataset_util `
in `to_tfrecords.py` module

**Comment by karstenBehrendt** [comment]
Hi, I added an import hint to the file
```
# https://github.com/tensorflow/models/research needs to be on PYTHONPATH
# Those directories were reorganized after I wrote this script
# Alternatively: from models.research.object_detection_utils import dataset_util
from object_detection.utils import dataset_util  # models/research on PYTHONPATH
```

You need to have tensorflow/models installed (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html) and {your local path}/models/research on your PYTHONPATH

Feel free to reopen if that didn't work
